comment:
  header: Hi, there.
  footer: "\
    ---\n\n\
    > This is an automated comment created by the [peaceiris/actions-label-commenter]. \
    Responding to the bot or mentioning it won't have any effect.\n\n\
    [peaceiris/actions-label-commenter]: https://github.com/peaceiris/actions-label-commenter"

labels:
  - name: invalid
    labeled:
      issue:
        body: |
          Thank you @{{ pull_request.user.login }} for opening the issue.
          Please follow the issue templates if applicable, or use [Discussions](https://github.com/danmyway/tesar/discussions).
        action: close
      pr:
        body: Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        action: close
    unlabeled:
      issue:
        body: Thank you for following the template. The repository owner will reply.
        action: open
  - name: wontfix
    labeled:
      issue:
        body: This will not be worked on but we appreciate your contribution.
        action: close
    unlabeled:
      issue:
        body: This has become active again.
        action: open
  - name: duplicate
    labeled:
      issue:
        body: Closing this issue, it already exists.
        action: close
      pr:
        body: Closing this pull request, it already exists.
        action: close
    unlabeled:
      issue:
        body: This has become active again.
        action: open
      pr:
        body: This has become active again.
        action: open
  - name: good first issue
    labeled:
      issue:
        body: This issue is easy for contributing. Everyone can work on this.
  - name: proposal
    labeled:
      issue:
        body: Thank you @{{ issue.user.login }} for suggesting this. Someone will take a look at this shortly.
  - name: bug
    labeled:
      issue:
        body: Thank you @{{ issue.user.login }} for submitting the bug report. Someone will take a look at this shortly.
  - name: resolved
    labeled:
      issue:
        body: |
          This issue has been **LOCKED** by being resolved!

          The issue has been fixed and is therefore considered resolved.
          If you're not happy with the changes, open a new issue instead of responding to this one.
        action: close
        locking: lock
        lock_reason: resolved
